package com.mycompany.gui_yasmeen;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Date;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class register_patient extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(register_patient.class.getName());

    /**
     * Creates new form register_patient
     */
    public register_patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        doctor = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        db = new javax.swing.JTextField();
        patientname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(182, 227, 249));
        jPanel1.setLayout(null);

        jTextField1.setText(".......");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 290, 290, 40);

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Doctor Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 130, 150, 28);

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("phone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 300, 70, 28);

        address.setText("......");
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(190, 180, 290, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton3.setText("clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(280, 370, 72, 27);

        doctor.setText(".......");
        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        jPanel1.add(doctor);
        doctor.setBounds(690, 120, 290, 40);

        d.setForeground(new java.awt.Color(102, 102, 102));
        d.setText("yy-mm-dd");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d);
        d.setBounds(690, 180, 290, 40);

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("RegistrationDate");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 200, 180, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 240, 290, 40);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton2.setText("Save Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 360, 160, 35);

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Patient Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 160, 40);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Date of Bithday");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 250, 170, 40);

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 90, 30);

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 90, 30);

        db.setForeground(new java.awt.Color(102, 102, 102));
        db.setText("yy-mm-dd");
        jPanel1.add(db);
        db.setBounds(690, 250, 290, 40);

        patientname.setText("......");
        patientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientnameActionPerformed(evt);
            }
        });
        jPanel1.add(patientname);
        patientname.setBounds(190, 120, 290, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 55)); // NOI18N
        jLabel1.setText("Registrer Patient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 470, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientnameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        patientname.setText("");
    address.setText("");
    doctor.setText("");
    db.setText("");
    d.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                             
                                        
// --- 1) قراءة البيانات من الفورم ---
String fullName = patientname.getText().trim();  // الاسم كامل
String address1 = address.getText();
String doctor1 = doctor.getText();
String dateOfBirthStr = db.getText();
String registrationDateStr = d.getText();
String gender = jComboBox1.getSelectedItem().toString();
String phone = jTextField1.getText();        // حقل الهاتف

if (fullName.isEmpty() || doctor1.isEmpty()) {
    JOptionPane.showMessageDialog(this, "يرجى تعبئة جميع الحقول المطلوبة");
    return;
}

// --- تقسيم الاسم إلى First / Middle / Last ---
String firstName = "";
String middleName = "";
String lastName = "";

String[] parts = fullName.split(" +");  // تفصل عند الفراغات

if (parts.length == 1) {
    firstName = parts[0];
} else if (parts.length == 2) {
    firstName = parts[0];
    lastName = parts[1];
} else {
    firstName = parts[0];
    lastName = parts[parts.length - 1];

    // الباقي يصبح Middle Name
    StringBuilder mid = new StringBuilder();
    for (int i = 1; i < parts.length - 1; i++) {
        mid.append(parts[i]).append(" ");
    }
    middleName = mid.toString().trim();
}

try {
    Connection con = database.getConnection();

    // تحويل التواريخ إلى java.sql.Date
    java.sql.Date dob = java.sql.Date.valueOf(dateOfBirthStr);      // تاريخ الميلاد
    java.sql.Date regDate = java.sql.Date.valueOf(registrationDateStr); // تاريخ التسجيل

    // ----------------- INSERT في جدول person -----------------
    String insertPerson =
        "INSERT INTO person (fname, mname, lname, gender, address, db, phone) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING person_id";

    PreparedStatement pstPerson = con.prepareStatement(insertPerson);
    pstPerson.setString(1, firstName);
    pstPerson.setString(2, middleName);
    pstPerson.setString(3, lastName);
    pstPerson.setString(4, gender);
    pstPerson.setString(5, address1);
    pstPerson.setDate(6, dob);
    pstPerson.setString(7, phone);

    ResultSet rs = pstPerson.executeQuery();

    int personID = 0;
    if (rs.next()) {
        personID = rs.getInt("person_id");
    } else {
        JOptionPane.showMessageDialog(this, "خطأ: لم يتم إنشاء person_id!");
        return;
    }

    String fName = "";

String lName = "";

String[] partss = doctor1.split(" +");  // تفصل عند الفراغات

if (partss.length == 1) {
    // الاسم كلمة واحدة
    firstName = partss[0];
    lastName = ""; 
} else {
    // أول كلمة = فيرست
    fName = partss[0];
    // آخر كلمة = لاست
    lName = partss[partss.length - 1];
}

  
// ----------------- INSERT في جدول patient -----------------


    String insertPatient =
        "INSERT INTO patient (person_id, doctor_fname,doctor_lname, registrationdate) VALUES (?, ?,?, ?)";

    PreparedStatement pstPatient = con.prepareStatement(insertPatient);
    pstPatient.setInt(1, personID);
    pstPatient.setString(2, fName );
    pstPatient.setString(3,lName );
    pstPatient.setDate(4, regDate);

    pstPatient.executeUpdate();

    JOptionPane.showMessageDialog(this, "تم إضافة المريض بنجاح!");

    

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "خطأ في حفظ البيانات: " + e.getMessage());
}


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField d;
    private javax.swing.JTextField db;
    private javax.swing.JTextField doctor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField patientname;
    // End of variables declaration//GEN-END:variables
}
