/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui_yasmeen;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class salary extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(salary.class.getName());

    /**
     * Creates new form salary
     */
    public salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtEmployeeId = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoursPerDay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 270, 260, 50);

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 55)); // NOI18N
        jLabel1.setText("your salary is :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 420, 100);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 280, 160, 50);
        jPanel1.add(txtEmployeeId);
        txtEmployeeId.setBounds(90, 120, 130, 40);
        jPanel1.add(txtMonth);
        txtMonth.setBounds(330, 120, 130, 40);
        jPanel1.add(txtYear);
        txtYear.setBounds(530, 120, 120, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 60, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("MONTH");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 130, 70, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("YEAR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 130, 60, 25);

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel6.setText("Enter the number of hour ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 280, 30);

        txtHoursPerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursPerDayActionPerformed(evt);
            }
        });
        jPanel1.add(txtHoursPerDay);
        txtHoursPerDay.setBounds(320, 200, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 try {
    int employeeId = Integer.parseInt(txtEmployeeId.getText());
    int month = Integer.parseInt(txtMonth.getText());
    int year = Integer.parseInt(txtYear.getText());
    int hoursPerDay = Integer.parseInt(txtHoursPerDay.getText());

    int hourRate = 15;

    Connection con = database.getConnection();

    // 1️⃣ التأكد إن الموظف موجود
    String checkSql = "SELECT lsnsm FROM laboratorystaff WHERE lsnsm = ?";
    PreparedStatement psCheck = con.prepareStatement(checkSql);
    psCheck.setInt(1, employeeId);

    ResultSet rs = psCheck.executeQuery();

    if (rs.next()) {

        int daysInMonth = java.time.YearMonth.of(year, month).lengthOfMonth();
        double salary = (daysInMonth-4 )* hoursPerDay * hourRate;

        // 2️⃣ تحديث الراتب + السنة + الشهر
        String updateSql = """
            UPDATE laboratorystaff
            SET salary = ?,
                work_year = ?,
                work_month = ?
            WHERE lsnsm = ?
        """;

        PreparedStatement psUpdate = con.prepareStatement(updateSql);
        psUpdate.setDouble(1, salary);
        psUpdate.setInt(2, year);
        psUpdate.setInt(3, month);
        psUpdate.setInt(4, employeeId);

        psUpdate.executeUpdate();

        // 3️⃣ عرض النتيجة
        jLabel2.setText("الراتب الشهري: " + salary + " شيقل");
        JOptionPane.showMessageDialog(this, "تم تحديث الراتب والسنة والشهر بنجاح ✅");

    } else {
        JOptionPane.showMessageDialog(this, "الموظف غير موجود");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "خطأ: " + e.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtHoursPerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursPerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursPerDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new salary().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtHoursPerDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
