package com.mycompany.gui_yasmeen;

import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class TEST_SCREEN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TEST_SCREEN.class.getName());

    /**
     * Creates new form TEST_SCREEN
     */
    public TEST_SCREEN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        hba1c = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ferritin = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        glucose = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbc = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        creatinine = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tsh = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        urine = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("View Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("View Details");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(370, 250, 121, 36);

        hba1c.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        hba1c.setForeground(new java.awt.Color(102, 102, 255));
        hba1c.setText("HB A1C");
        jPanel1.add(hba1c);
        hba1c.setBounds(300, 260, 52, 20);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("View Details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(370, 190, 121, 39);

        ferritin.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        ferritin.setForeground(new java.awt.Color(102, 102, 255));
        ferritin.setText("Ferritin");
        jPanel1.add(ferritin);
        ferritin.setBounds(300, 200, 52, 20);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("View Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 130, 122, 38);

        glucose.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        glucose.setForeground(new java.awt.Color(102, 102, 255));
        glucose.setText("Glucose");
        jPanel1.add(glucose);
        glucose.setBounds(300, 130, 62, 31);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD, jButton1.getFont().getSize()+2));
        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 130, 122, 40);

        cbc.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbc.setForeground(new java.awt.Color(102, 102, 255));
        cbc.setText("CBC");
        jPanel1.add(cbc);
        cbc.setBounds(50, 130, 37, 35);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("View Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(100, 190, 122, 39);

        creatinine.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        creatinine.setForeground(new java.awt.Color(102, 102, 255));
        creatinine.setText("Creatinine");
        jPanel1.add(creatinine);
        creatinine.setBounds(20, 190, 77, 35);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(jButton4.getFont().deriveFont(jButton4.getFont().getStyle() | java.awt.Font.BOLD, jButton4.getFont().getSize()+2));
        jButton4.setText("View Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(100, 250, 122, 35);

        tsh.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        tsh.setForeground(new java.awt.Color(102, 102, 255));
        tsh.setText("TSH");
        jPanel1.add(tsh);
        tsh.setBounds(30, 250, 52, 35);

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setText("View Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(650, 130, 121, 36);

        urine.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        urine.setForeground(new java.awt.Color(102, 102, 255));
        urine.setText("Urine analysis");
        jPanel1.add(urine);
        urine.setBounds(540, 140, 101, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Available Tests :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 30, 262, 48);

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\577e7c77-f514-4e7d-8c38-2d819206ef12.jpg")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 0, 125, 114);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:Ferritin
        String testName = ferritin.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);

    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String testName = creatinine.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
 liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    liveView.setVisible(true);


    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String testName = tsh.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
   liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);


    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           String testName = glucose.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
  veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
    liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);

    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           String testName = tsh.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);

    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           String testName = tsh.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
    liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);


    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
           String testName = urine.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
   veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    liveView.setVisible(true);

    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // الحصول على اسم الفحص المرتبط بهذا الزر
    String testName = cbc.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
  veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
   liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);


    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:HB A1C
        String testName = hba1c.getText(); // jLabelTestName = Label يحتوي اسم الفحص

    // تمرير اسم الفحص للشاشة الجديدة
  veiw liveView = new veiw(testName);
    liveView.setLocation(700, 400);
 liveView.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);


    liveView.setVisible(true);

    // غلق شاشة الاختبارات إذا تحبي
    this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cbc;
    private javax.swing.JLabel creatinine;
    private javax.swing.JLabel ferritin;
    private javax.swing.JLabel glucose;
    private javax.swing.JLabel hba1c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tsh;
    private javax.swing.JLabel urine;
    // End of variables declaration//GEN-END:variables
}
